#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

TZ_NAME="Asia-Jerusalem"
ROOT="/storage/emulated/0/PROJECT/SAFE_V3"
BUILD_ORIGIN="${ROOT}/BUILD__2026-01-21__22-01__${TZ_NAME}"
HUB="${BUILD_ORIGIN}/HUB__SoulInPsyAbstract_AI_Termux_OS"

# current scan output (shared OUT, because it was reused)
OUT_CURRENT="${HUB}/HUB_04__FIXATIONS_LOG/SCAN__CREATION_EVIDENCE__ORIGIN__2026-01-21__22-05__${TZ_NAME}"

# target names
OUT_V2="${HUB}/HUB_04__FIXATIONS_LOG/SCAN__CREATION_EVIDENCE__ORIGIN__V2__FILES_62__2026-01-21__22-05__${TZ_NAME}"
OUT_V1_NOTE="${HUB}/HUB_04__FIXATIONS_LOG/FIXATION__CANON_ORIGIN_SNAPSHOT__V1__FILES_52__2026-01-21__22-05__${TZ_NAME}.txt"

# hard checks
if [ ! -d "$HUB" ]; then
  echo "ERROR: HUB not found: $HUB"
  exit 2
fi

if [ ! -d "$OUT_CURRENT" ]; then
  echo "ERROR: OUT_CURRENT not found: $OUT_CURRENT"
  exit 3
fi

# --------------------------------------------------
# 1) FIXATION NOTE FOR V1 (52) — terminal-only, no manual edits
# --------------------------------------------------
cat <<'EOF_V1' > "$OUT_V1_NOTE"
FIXATION · CANON ORIGIN SNAPSHOT (V1)

ENTITY:
SoulInPsyAbstract AI Termux OS

ORIGIN BUILD:
2026-01-21 22:01 (Asia/Jerusalem)

SCAN MOMENT:
2026-01-21 22:05 (Asia/Jerusalem)

MODE: LEGAL · DECLARATIVE · READ-ONLY
EXECUTION_CONTEXT=NONE
RUNTIME=LOCAL
CLAIMS=NONE

CANON_ORIGIN_SNAPSHOT:
FILES_SCANNED = 52
FIRST_ORIGIN_SCAN = TRUE

NOTE:
This value refers to the FIRST run of the ORIGIN scan executed against:
BUILD__2026-01-21__22-01__Asia-Jerusalem/HUB__SoulInPsyAbstract_AI_Termux_OS

Later scans may include additional forensic artifacts generated by the scan itself.
RETROACTIVE_MUTATION = FORBIDDEN

END OF FIXATION
EOF_V1

# --------------------------------------------------
# 2) RENAME CURRENT OUT -> V2 (62)
# (No deletion, no content change. Pure move/rename.)
# --------------------------------------------------
if [ -e "$OUT_V2" ]; then
  echo "ERROR: OUT_V2 already exists: $OUT_V2"
  exit 4
fi

mv "$OUT_CURRENT" "$OUT_V2"

# --------------------------------------------------
# 3) ADD V2 FIXATION INSIDE V2 FOLDER (self-contained)
# --------------------------------------------------
cat <<'EOF_V2' > "$OUT_V2/FIXATION__ORIGIN_SCAN__V2__FILES_62__2026-01-21__22-05__Asia-Jerusalem.txt"
FIXATION · ORIGIN SCAN (V2)

ENTITY:
SoulInPsyAbstract AI Termux OS

ORIGIN BUILD:
2026-01-21 22:01 (Asia/Jerusalem)

SCAN MOMENT:
2026-01-21 22:05 (Asia/Jerusalem)

MODE: LEGAL · DECLARATIVE · READ-ONLY
EXECUTION_CONTEXT=NONE
RUNTIME=LOCAL
CLAIMS=NONE

STATUS:
FILES_SCANNED = 62
V2_INCLUDES_SCAN_ARTIFACTS = TRUE

DECLARATION:
This folder contains scan-generated artifacts (TSV/MANIFEST/SHA/TAG/FIXATION),
therefore it represents the post-fixation state.

RETROACTIVE_MUTATION = FORBIDDEN

END OF FIXATION
EOF_V2

# --------------------------------------------------
# 4) PRINT EYES SUMMARY
# --------------------------------------------------
echo "OK · PATCH APPLIED"
echo "V1 FIXATION (52) -> $OUT_V1_NOTE"
echo "V2 FOLDER (62)   -> $OUT_V2"
echo "V2 FIXATION      -> $OUT_V2/FIXATION__ORIGIN_SCAN__V2__FILES_62__2026-01-21__22-05__Asia-Jerusalem.txt"
